module.exports = {
  GOOGLE_OAUTH_CLIENT_ID: process.env.GOOGLE_OAUTH_CLIENT_ID,
  GOOGLE_OAUTH_CLIENT_SECRET: process.env.GOOGLE_OAUTH_CLIENT_SECRET,
  GOOGLE_OAUTH_CALLBACK_URL: process.env.COOKIEKEY,
  MONGODB_URI: process.env.MONGODB_URI,
  COOKIEKEY: process.env.COOKIEKEY,
};
